### ISSUE TITLE
Dynamic gas for sha3

### ISSUE THREAD

**Issue by LucasLvy** [sayajin-labs/kakarot#120]
Sha3 gas cost is static, change it to be dynamic following these instructions:
```txt
minimum_word_size = (size + 31) / 32

static_gas = 30
dynamic_gas = 6 * minimum_word_size + memory_expansion_cost
```
The memory expansion cost explanation can be found [here](https://www.evm.codes/about).

**Comment by ClementWalter** [comment]
I'm on it

**Comment by ClementWalter** [comment]
✅
