### ISSUE TITLE
feat: implement 0xA0 - LOG0

### ISSUE THREAD

**Issue by abdelhamidbakhta** [sayajin-labs/kakarot#178]
### Since

Frontier

### Group

Logging Operations

### Description

Append log record with one topic. 

[Geth implementation](https://github.com/ethereum/go-ethereum/blob/master/core/vm/instructions.go#L840)

Notes
This instruction has no effect on the EVM state. See [here](https://ethereum.org/en/developers/docs/smart-contracts/anatomy/#events-and-logs).

Stack input
offset: byte offset in the [memory](https://www.evm.codes/about) in bytes.
size: byte size to copy.
topic1: 32-byte value.
topic2: 32-byte value.
Error cases
The state changes done by the current context are [reverted](https://www.evm.codes/?fork=grayGlacier#FD) in those cases:

Not enough gas.
Not enough values on the stack.
The current execution context is from a [STATICCALL](https://www.evm.codes/#FA) (since Byzantium fork).
Dynamic gas
static_gas = 375
dynamic_gas = 375 * topic_count + 8 * size + memory_expansion_cost

**Comment by Eikix** [comment]
Assigned to Gregory!
