### ISSUE TITLE
feat:  Compute intrinsic gas cost

### ISSUE THREAD

**Issue by LucasLvy** [sayajin-labs/kakarot#207]
# Feature Request

**Describe the Feature Request**

**Describe Preferred Solution**

**Describe Alternatives**

**Related Code**

**Additional Context**

**If the feature request is approved, would you be willing to submit a PR?**
Yes / No _(Help can be provided if you need assistance submitting a PR)_

**Comment by Eikix** [comment]
What is the scope of this issue @LucasLvy ?

**Comment by Eikix** [comment]
Closing in order to open more targeted issues at buggy intrinsic gas costs
