### ISSUE TITLE
doc: create documentation for Kakarot

### ISSUE THREAD

**Issue by Eikix** [sayajin-labs/kakarot#220]
Creating a documentation page for Kakarot (interaction with the smart contract, API description, RPC endpoint, etc.)

**Comment by matthieuauger** [comment]
Resources to be documented:

- interacting with the smart contract
- API description
- RPC endpoint
- deployment procedure
- how to add a new solidity smart contract in the testsuite

**Comment by Eikix** [comment]
I think we could reduce the scope of this issue and ask for each bulletpoint in a single issue / PR? wdyt @matthieuauger 
For this issue, it could be simply how to add a new solidity smart contract in the testsuite
