### ISSUE TITLE
feat: Get execution resources

### ISSUE THREAD

**Issue by LucasLvy** [sayajin-labs/kakarot#230]
# Feature Request

**Describe the Feature Request**
After each call get the number of steps required + the number of builtins used

**Describe Preferred Solution**
Get these informations in `res.call_info.execution_resources` in the python test file

**Describe Alternatives**

**Related Code**

**Additional Context**

**If the feature request is approved, would you be willing to submit a PR?**
Yes / No _(Help can be provided if you need assistance submitting a PR)_

**Comment by Eikix** [comment]
I think this is done
Can we close it?

**Comment by ClementWalter** [comment]
I think so yes, the merged PR #237 does this
