### ISSUE TITLE
Create a bytepacking library for Kakarot: optimizing storage of bytes array

### ISSUE THREAD

**Issue by Eikix** [sayajin-labs/kakarot#239]
Currently, Kakarot is developed using a naive implementation.

As such, bytes (8-bit words in memory) are stored in a single felt. This means that a felt (up to 251-bit of information) is used to store only 8 bits.

The aim of this issue is to pave the way for byte packing.

Best outcome: 31 bytes per felt -> maximum efficiency
Mild outcome: 16 bytes per felt -> ok efficiency
Bad outcome: 1 byte per felt -> current efficiency

**Comment by Eikix** [comment]
@danilowhk is currently assigned

**Comment by danilowhk** [comment]
I can do this one

**Comment by Eikix** [comment]
I believe @ClementWalter and @danilowhk will tackle this issue in the coming days:)

**Comment by danilowhk** [comment]
Yes haha :)

**Comment by ClementWalter** [comment]
Closing this as bytes16 packing was merged 3 days ago. Should we want to investigate further with, e.g. bytes31 packing, we'll create another issue, but this one is AKAIF resolved.
