### ISSUE TITLE
feat: Add .sol Solidity Smart contract used for integration testing and benchmarking files to our repo

### ISSUE THREAD

**Issue by Eikix** [sayajin-labs/kakarot#244]
# Feature Request

**Describe the Feature Request**

As discussed with @ClementWalter: 

> in the context of open contribution and shared results, we really need to record everything, and be able to reproduce any claimed result with 100% confidence. No one outside of this telegram will give any credit to a result that is not properly documented with a way to clearly reproduce it

Add .sol Solidity Smart contract used for integration testing and benchmarking files to our repo

**Describe Preferred Solution**

**Describe Alternatives**

**Related Code**

**Additional Context**

**If the feature request is approved, would you be willing to submit a PR?**
Yes / No _(Help can be provided if you need assistance submitting a PR)_

**Comment by Eikix** [comment]
I think @abdelhamidbakhta is starting an implementation

**Comment by Eikix** [comment]
Clement is currently working on this

**Comment by matthieuauger** [comment]
Fixed in https://github.com/sayajin-labs/kakarot/pull/245
