### ISSUE TITLE
feat: implement 0xFD REVERT

### ISSUE THREAD

**Issue by ClementWalter** [sayajin-labs/kakarot#249]
### Since

Byzantium

### Group

System Operations

### Description

0xFD - REVERT

Stop the current context execution, revert the state changes (see [STATICCALL](https://www.evm.codes/#FA) for a list of state changing opcodes) and return the unused gas to the caller. It also reverts the gas refund to its value before the current context. If the execution is stopped with REVERT, the value 0 is put on the stack of the calling context, which continues to execute normally. The [return data](https://www.evm.codes/about) of the calling context is set as the given chunk of memory of this context.

**Comment by pedrobergamini** [comment]
May I open a PR on this one?

**Comment by matthieuauger** [comment]
@pedrobergamini sure, welcome onboard! Can you please share here a bit of the technical strategy you want to implement? It can avoid rework, we'll be happily give you feedback on it and answer questions if you have

**Comment by pedrobergamini** [comment]
Hey @matthieuauger! I was discussing with @Eikix and @LucasLvy in telegram, the idea is to initially implement this using Starknet's native revert and just reading the return data to create a shortstring from it and use it as the revert reason.

**Comment by matthieuauger** [comment]
Awesome! LFG 🚀

**Comment by pedrobergamini** [comment]
Opened a PR, let me know what you guys think on the implementation suggestion #277
