### ISSUE TITLE
bug: fix "skipped" tests

### ISSUE THREAD

**Issue by ClementWalter** [sayajin-labs/kakarot#254]
# Bug Report

**Current behavior:**

Few tests are currently skipped (pytest.mark.skip) because they were actually failing when we refacto the test suite to check the whole output (stack, memory) instead of (peek, one push, etc.).

**Expected behavior:**

We need to study these test cases to remove the skip and eventually solve bugs

**Related code:**

See tests marked with `pytest.mark.skip`

**Comment by matthieuauger** [comment]
mstore test unskipped: https://github.com/sayajin-labs/kakarot/pull/304

**Comment by matthieuauger** [comment]
jumps tests unskipped: https://github.com/sayajin-labs/kakarot/pull/305/files

**Comment by ClementWalter** [comment]
we have `test_deploy_erc20` as well

**Comment by Eikix** [comment]
good catch! do you want to do it?

**Comment by ClementWalter** [comment]
I can have a look but this needs to be the last one fixed, so after basefee because the deployment of the erc20 uses more bytecode so beter start with the cleanest possible state

**Comment by Eikix** [comment]
if I remember correctly, basefee posed a problem because Starknet does not have a fee market and does not implement the same gas rules as Ethereum

**Comment by ClementWalter** [comment]
just running it now to see if there's actually something to do or if it's already solved

**Comment by ClementWalter** [comment]
issue is still preset, I'll investigate

**Comment by ClementWalter** [comment]
closing this as I've removed the bytecode test from ERC20 because it does not indeed belong to this test. `deploy` or other opcodes (CODECOPY) may be missing some tests (see #295) but it's not ERC20 responsibility to patch them.

consequently only BASEFEE is still skipped as of today.
