### ISSUE TITLE
feat: implement 0xF3 - RETURN

### ISSUE THREAD

**Issue by matthieuauger** [sayajin-labs/kakarot#257]
### Since

Frontier

### Group

System operations

### Description

0xF3 - RETURN

see https://www.evm.codes/#f3?fork=merge

**Comment by Eikix** [comment]
Can we consider this opcode done @danilowhk ?

**Comment by danilowhk** [comment]
Hey @Eikix I actually found a small bug yesterday(while working on felt packing). 

I think it can be considered done once we have the tests? Which I believe @pedrobergamini is working on? If not I can make a Pr for tests :)

**Comment by danilowhk** [comment]
Just the tests are missing, which I believe @0xMentorNotAPseudo is working on :)

**Comment by Eikix** [comment]
@pedrobergamini can you confirm this information:)?

**Comment by pedrobergamini** [comment]
Hey @Eikix, yes I will have the tests done this week

**Comment by ClementWalter** [comment]
This is NOT done: RETURN should update the `return_data` and not `alloc` a new segment.

**Comment by ClementWalter** [comment]
this has been fixed during #335
