### ISSUE TITLE
feat: implement 0xF4 - DELEGATECALL

### ISSUE THREAD

**Issue by matthieuauger** [sayajin-labs/kakarot#258]
### Since

Byzantium

### Group

System operations

### Description

0xF4 - DELEGATECALL

see https://www.evm.codes/#f4?fork=merge

**Comment by Eikix** [comment]
First implementation is proposed by @ClementWalter in https://github.com/sayajin-labs/kakarot/pull/335, will need a few tweaks to be fully operational:)

**Comment by ClementWalter** [comment]
See comment for issue #256
