### ISSUE TITLE
feat: disable some opcodes for STATICCALL

### ISSUE THREAD

**Issue by matthieuauger** [sayajin-labs/kakarot#260]
### Description

0x -

**Comment by Eikix** [comment]
First implementation is proposed by @ClementWalter in #335, will need a few tweaks to be fully operational:)

**Comment by ClementWalter** [comment]
Apart from the gas usage issue common with the 4 CALLs opcodes, STATICCALL needs also to disable few opcodes: 

> The disallowed instructions are [CREATE](https://www.evm.codes/#F0), [CREATE2](https://www.evm.codes/#F5), [LOG0](https://www.evm.codes/#A0), [LOG1](https://www.evm.codes/#A1), [LOG2](https://www.evm.codes/#A2), [LOG3](https://www.evm.codes/#A3), [LOG4](https://www.evm.codes/#A4), [SSTORE](https://www.evm.codes/#55), [SELFDESTRUCT](https://www.evm.codes/#FF) and [CALL](https://www.evm.codes/#F1) if the [value](https://www.evm.codes/#34) sent is not 0.
