### ISSUE TITLE
feat: implement 0xFF - SELFDESTRUCT

### ISSUE THREAD

**Issue by matthieuauger** [sayajin-labs/kakarot#261]
### Since

Frontier

### Group

System Operations

### Description

0xFF - SELFDESTRUCT

See https://www.evm.codes/#ff?fork=merge 

### Possible implementation

To destruct a contract in kakarot, it is enough in our case to:
1. overwrite the bytecode of the contract to 0: it's required to write as many 0s as the contract bytecode_len to clean everything
2. remove the address from the registry

The documentation says: 
> the current account is registered to be destroyed, and will be at the end of the current transaction. 
so it looks necessary to add a `destroy_registered_len: felt`, `destroy_registered: felt*` array to the `ExecutionContext` to store this information.

In the `instructions.cairo:run` function, we would then change this:
```
        if (stopped != FALSE) {
            if (is_parent_root != FALSE) {
                return ctx;
            }
```

to actually do the removal of the registered contracts.

Eventually a possible implementation would:

1. in the `SystemOperations.exec_syscall`:

    1. transfer the fund to the given address (revert if error) (see BALANCE for code example)
    2. add the current `ExecutionContext.evm_contract_address` to `ExecutionContext.destroy_registered` array.

2. in the `system_operations.cairo`, create a `SelfDestructHelper` to write the logic

    1. retrieve starknet_contract_address from evm_contract_address
    2. overwrite contract account bytecode with 0s
    3. overwrite registry contract with 0s

3. in the `run` function, when a context is `stopped`

    1. if the parent is root,  apply the `SelfDestructHelper`
    2. otherwise, update the `finalize_calling_context` to append to the calling context `destroy_registered` the values from the sub context

**Comment by petarcalic99** [comment]
I can check this out:)

**Comment by matthieuauger** [comment]
Hello @petarcalic99 how are you doing? Do you still want to work on this opcode?

**Comment by petarcalic99** [comment]
Hey ! I am sorry i was really busy last week, i will be able to continue to work on it these days but if someone else wants to take the issue i m fine with it also.

**Comment by matthieuauger** [comment]
@petarcalic99 No worries, I was just doing a check-up on the issues. Great news if you can continue to work on it 🚀

**Comment by hurrikaanig** [comment]
Can I continue this ? ✌️

**Comment by petarcalic99** [comment]
Sure, i got stuck and don't have a lot of time right now. If you want text me on telegram so i can show you what i have done.
