### ISSUE TITLE
refactor: Refactor function signatures to always enforce (arr_len, len) -> .... 

### ISSUE THREAD

**Issue by Eikix** [sayajin-labs/kakarot#269]
in the words of @ClementWalter : 

> back to the code, is there a reason why we just used everywhere arr, arr_len and not arr_len, arr as it is supposed to be the case at least for argumenst in calldata

> I think that  arr_len, arr is better because:
> 1. it’s consistent with the calldata way
> 2. arrays in solidity are encoded like that: basically in solidity we would just have arr: felt* and [arr] = arr_len (maybe this could also be adapted for cairo 1.0 ?)```

> in short my point:
> - we need to do always the same to have a standard for this question
> - cairo in some contexts enforce arr_len, arr
> - solidity uses len, values in its internal encoding scheme
> => we should do this everywhere, ie putting the lenght of an array before the array```

**Comment by Eikix** [comment]
Good first issue

**Comment by ptisserand** [comment]
Hi, can I work on this issue?

**Comment by matthieuauger** [comment]
@ptisserand sure!

**Comment by ptisserand** [comment]
I was wondering if I have also to change this kind of helpers:
`func bytes_i_to_uint256{range_check_ptr}(val: felt*, i: felt, res: Uint256) -> Uint256`
into
`func bytes_i_to_uint256{range_check_ptr}(arr_len: felt, arr: felt*, res: Uint256) -> Uint256`
