### ISSUE TITLE
performance: migrate to cairo-rs (rust Cairo VM)

### ISSUE THREAD

**Issue by matthieuauger** [sayajin-labs/kakarot#270]

**Comment by Eikix** [comment]
There are many different steps in this milestone.

Step 1: Have Cairo code run in a Rust VM, while the larger process (Starknet VM) in ran in Python. Federico's team from Lambda Class has implemented a CairoVM in Rust and has successfully wrapped it in Python. Soon, Kakarot tests will be able to run on the cairo-rs-py vm!

Step 2: Everything runs in Rust, in a Python process.

Step 3: Everything runs in Rust! In a Rust process.
