### ISSUE TITLE
refactor: manipulate decimal number in tests

### ISSUE THREAD

**Issue by matthieuauger** [sayajin-labs/kakarot#273]
In some integrations tests we manipule hexadecimal values directly for numbers.

Example in [erc20 integration test](https://github.com/sayajin-labs/kakarot/blob/main/tests/integrations/test_zk_evm.py#L76).

```python
await erc_20.mint(addresses[2], 0x164, caller_address=caller_addresses[1]) 
```

We could improve test readability by using decimal values casted in hex

**Comment by matthieuauger** [comment]
Hello @mnekx, my apologies the issue I created is misleading. We shouldn't need to cast anything, code already manipulates integers in the hexadecimal form. We should be able to simply replace these values by their decimal equivalent!

**Comment by mnekx** [comment]
anhaa, okay :+1:

**Comment by matthieuauger** [comment]
@mnekx are you still interested in picking this issue?

**Comment by mnekx** [comment]
Yes I am. but, was it opened by mistake? will it be enough to replace hex
numbers with their decimal equivalent?

**Comment by matthieuauger** [comment]
Yes definitely the purpose here is to gain readability by removing non essential hex values in the code, the fact that we won’t need to cast is even better for readability :)

**Comment by mnekx** [comment]
ok then, I am on it
