### ISSUE TITLE
feat: Add coverage and resources usage in CI

### ISSUE THREAD

**Issue by ClementWalter** [sayajin-labs/kakarot#280]
# Feature Request

The command `make test-no-log` returns a coverage report and a resources usage report.
These reports should be used in the CI to block PRs that don't meet a given standard.

**Describe Preferred Solution**

The CI should take this values from their own test and commit them to the branch.
Not sure if codecov or similar tools can make it.

**Describe Alternatives**

Use github actions and possible custom script.

**Comment by matthieuauger** [comment]
Thanks @ClementWalter, I'm adding this to the "code coverage improvement" EPIC for v0.1: https://github.com/sayajin-labs/kakarot/issues/274

**Comment by Eikix** [comment]
I think a good way to go about this would be:

- introduce a staging branch (unprotected),
- upon merging a PR into staging, an action runs to generate resource files and commits them to the staging branch,
- then, upon review by core maintainers (that actions committed okay files), staging is merged into main branch.
- (a job runs to merge main back into staging to guarantee consistency in gitflow)

**Comment by Eikix** [comment]
@ClementWalter will take on this daunting task 🔥 🏆  👷
