### ISSUE TITLE
dev: refactor Memory.load(offset: felt) to Memory.load_n(offset: felt, n: felt) and have exec_mload opcode call Memory.load_n(...,32)

### ISSUE THREAD

**Issue by Eikix** [sayajin-labs/kakarot#287]
As seen in #277 with @ClementWalter, it would be beneficial to refactor `Memory.load` to `Memory.load_n` to have better granularity for loading memory chunks.

**Comment by hurrikaanig** [comment]
Hey @Eikix, I'm the one who asked for this issue on Discord :)

**Comment by Eikix** [comment]
Done:)!
