### ISSUE TITLE
Add tests for opcodes SWAPX

### ISSUE THREAD

**Issue by matthieuauger** [sayajin-labs/kakarot#316]
[codecov](https://app.codecov.io/gh/sayajin-labs/kakarot/blob/main/src/kakarot/instructions.cairo) coverage reports that the exec_swap_x are not covered.

To tackle this issue conception would be: 

- create test_exchange_operations.cairo and add related tests
- create test_exchange_operations.py in tests/units/instructions to get the tests run by our testsuite
- TestHelpers implemented [here](https://github.com/sayajin-labs/kakarot/pull/306) can be used to initialize context

Validation procedure: codecov in the PR set the exec_swap_x as covered

**Comment by jobez** [comment]
Let's get it covered!
