### ISSUE TITLE
Test Coverage for XOR and BYTE

### ISSUE THREAD

**Issue by matthieuauger** [sayajin-labs/kakarot#329]
The exec_xor and exec_byte are not tested yet.
See [codecov](https://app.codecov.io/gh/sayajin-labs/kakarot/blob/main/src/kakarot/instructions/comparison_operations.cairo)

Strategy: add unit tests in test_comparison_operations 
Examples unit tests for other opcodes: test_push_operations.py

**Comment by ptisserand** [comment]
Hi, can I work on this issue?

**Comment by matthieuauger** [comment]
Sure, issue is yours!

**Comment by ptisserand** [comment]
I have look at tests for OR https://github.com/sayajin-labs/kakarot/blob/883b6da2329897aee9205da9206889e848f256ec/tests/unit/src/kakarot/instructions/test_comparison_operations.cairo#L391
and it seems that only "boolean" OR is tested.

Should I do the same for XOR or should I write bitwise XOR tests ?
