### ISSUE TITLE
Test Coverage for RETURNDATACOPY

### ISSUE THREAD

**Issue by matthieuauger** [sayajin-labs/kakarot#331]
The exec_returndatacopy is not tested yet.
See [codecov](https://app.codecov.io/gh/sayajin-labs/kakarot/blob/main/src/kakarot/instructions/environmental_information.cairo)

Strategy: add unit tests in a new test_environmental_information 
Examples unit tests for other opcodes: test_push_operations.py

**Comment by hurrikaanig** [comment]
May I take it :) @matthieuauger

**Comment by matthieuauger** [comment]
Of course! 🚀 I'm available if you have any questions on this topic

**Comment by Eikix** [comment]
Closing, as #348 solves it
