### ISSUE TITLE
feat: integrate warm/cold account concepts in EXTCODEXXX opcodes

### ISSUE THREAD

**Issue by Eikix** [sayajin-labs/kakarot#340]
# Feature Request

As mentioned in the [EVM spec](https://www.evm.codes/about#accesssets): 
> Access sets have been introduced in the hardfork Berlin. They are kept per transaction (and not per call context). Two of them exist: the touched contracts addresses, and the touched contract storage slots. If an address or slot is present in the set, it is called 'warm', otherwise it is 'cold'. The dynamic cost of some opcodes depends on whether the address or slot is warm or cold.
Addresses: a set of contract addresses that have been touched in the current transaction. It is initialized with the sender and receiver (or the new contract address in case of a creation) of the transaction, as well as all the [precompiled contracts](https://www.evm.codes/precompiled). When an opcode accesses an address that is not present in the set, it adds it in it. The relevant opcodes are [EXTCODESIZE](https://www.evm.codes/#3B), [EXTCODECOPY](https://www.evm.codes/#3C), [EXTCODEHASH](https://www.evm.codes/#3F), [BALANCE](https://www.evm.codes/#31), [CALL](https://www.evm.codes/#F1), [CALLCODE](https://www.evm.codes/#F2), [DELEGATECALL](https://www.evm.codes/#F4), [STATICCALL](https://www.evm.codes/#FA), [CREATE](https://www.evm.codes/#F0), [CREATE2](https://www.evm.codes/#F5) and [SELFDESTRUCT](https://www.evm.codes/#FF).
Slots: a set of contract address and their storage slot keys that have been accessed. It is initialized to empty. When an opcode accesses a slot that is not present in the set, it adds it to it. The relevant opcodes are [SLOAD](https://www.evm.codes/#54) and [SSTORE](https://www.evm.codes/#55)
When a context reverts, the sets are also reverted to the state they had before that context.

For now, Kakarot will treat any account as cold and won't cache in memory "warm" accounts.

To do: make apparent these concepts and hard code the fact that accesses are cold. Gas consumed should be parametrised and therefore gas consumed should be in line with cold accounts.

**Describe the Feature Request**

**Describe Preferred Solution**

**Describe Alternatives**

**Related Code**

**Additional Context**

**If the feature request is approved, would you be willing to submit a PR?**
Yes / No _(Help can be provided if you need assistance submitting a PR)_

**Comment by Eikix** [comment]
In kakarot conversation: 
> Yep! So we also drop support for warm/cold accesses. this task would become simply hardcoding the cold access gas costs into kakarot and documenting in comments that we don't use warm access

**Comment by Eikix** [comment]
@jobez is this already done and I didn't see it?

**Comment by jobez** [comment]
Yeah, it is hard coded for cold gas access right now.
