### ISSUE TITLE
bug: deployed contracts bytecode differs from local bytecode

### ISSUE THREAD

**Issue by jobez** [sayajin-labs/kakarot#342]
# Bug Report

When doing integration tests for excodecopy, I ran into issues comparing the bytecode as it is stored in the registry (as written by deploy logic) from the bytecode as it exists locally.

**Kakarot version:**

v0.1.0.
**Current behavior:**

Extcodecopy writes to memory a contracts bytecode, but the bytecode in memory does not match the bytecode of the contract as compiled locally.

**Expected behavior:**

We expect the contract bytecode as written to memory to be the same as the locally compiled bytecode. Although there may be exceptions: https://docs.soliditylang.org/en/develop/contracts.html#call-protection-for-libraries. Needs clarification/investigation.

**Steps to reproduce:**

The two minimal cases can be seen by unskipping and running:

```
poetry run pytest -s -k test_extcodecopy_offset_and_size_gte_twenty_c
```

and

```
poetry run pytest -s -k test_extcodecopy_erc20
```

**Related code:**

You can see the logic in each of these tests.

```
insert short code snippets here
```

**Other information:**

@ClementWalter mentioned on telegram when I shared my first investigation of this 

> interesting. I realized as well that the test on bytecode (deployed VS stored) was failing for ERC20 as well, we had once an issue that I closed after refactoring the test. Codecopy is part of the non-tested opcodes so we’ll probably see something here 👀

**Comment by Eikix** [comment]
#369 does not solve #342, right ?

**Comment by ClementWalter** [comment]
I don't think so because when doing #369 we still add issues with deployed bytecode, which probably uses CODECOPY (not sure though)
