### ISSUE TITLE
feat: use gas in CALLs opcodes

### ISSUE THREAD

**Issue by ClementWalter** [sayajin-labs/kakarot#349]
# Feature Request

The gas args is not used when creating subcontexts.

**Describe Preferred Solution**

Fix `// TODO: Add support for gas limit` in `ExecutionContext.init_at_address`.

**Related Code**

`execution_context.cairo:init_at_address` and opcodes `CALL`, `CALLCODE`,  `STATICCALL` & `DELEGATECALL`.

**Additional Context**

Gas accounting in kakarot is currently erratic.

**Comment by Eikix** [comment]
I think this is a completed issue. What do you think @ClementWalter?

**Comment by ClementWalter** [comment]
> I think this is a completed issue. What do you think @ClementWalter?

it is, see https://github.com/sayajin-labs/kakarot/pull/373
