### ISSUE TITLE
feat: propose a specs / MVP for EVM -> Starknet RPC adapter

### ISSUE THREAD

**Issue by Eikix** [sayajin-labs/kakarot#354]
# Feature Request

**Describe the Feature Request**

As mentioned by @etashhh in #294, we'll be building a backend that acts as an adapter layer for Kakarot. 
There is a need to: 
- translate EVM RPC calls into Starknet messages
- translate Starknet messages into specific Kakarot calls that serve the right purpose

Example:
Bob wants to call `balanceOf()` on an ERC20 on Kakarot. He sends an EVM RPC call to Kakarot's backend.
Backend translates the call to Starknet RPC. 
Then, `balanceOf()` call is transformed to a `Kakarot.execute_at_address()` that calls `balanceOf()` 

**Describe Preferred Solution**

**Describe Alternatives**

**Related Code**

**Additional Context**

**If the feature request is approved, would you be willing to submit a PR?**
Yes / No _(Help can be provided if you need assistance submitting a PR)_

**Comment by Flydexo** [comment]
What do you mean by `parses ethereum account and deploys starknet account upon first connection` ?

**Comment by Eikix** [comment]
I think this is not the responsibility of the RPC layer to handle this.

Though I think what @etashhh meant is that owning a private key on Ethereum means owning an account (EOA). Whereas on Starknet only Account smart contracts allow for transacting with the chain. This typically means that there is some kind of reconciliation to be made.

I think the debate about reconciliating these two is in the scope of another issue / another piece of the architecture

**Comment by etashhh** [comment]
Yes, as @Eikix stated. I could have worded it much better 😅. Essentially there needs to be some reconciliation between the two.

**Comment by Flydexo** [comment]
So the users sends a normal EVM signed with an Ethereum address and the rpc sends the starknet transaction with the rpc starknet signature.

**Comment by Eikix** [comment]
Almost! I think for the signature to be valid, it need not be touched or tampered with.

This means that:
- the user sends a normal EVM signed with an Ethereum address
- the RPC does the translation it needs to do to make an EVM transaction become a Starknet transaction
    - in the Starknet tx's payload, there needs to still be an EVM tx and an EVM signature!
    - the Account Abstraction contract needs to be able to decode the tx and verify the signature

if you have another idea, let me know:)!

**Comment by Flydexo** [comment]
evm tx decoding on the AA almost done.

And found a simpler way for gas, just check that the EVM tx gas is the same as the starknet tx. If not refuse, if true the Starknet OS will handle it itself
