### ISSUE TITLE
feat: Precompile 0x01 ecRecover

### ISSUE THREAD

**Issue by Eikix** [sayajin-labs/kakarot#357]
# Feature Request

feat: Explore / propose strategy (if applicable, MVP implementation) for EVM Precompiled contract -> 0x01 ecRecover

https://www.evm.codes/precompiled

**Comment by feltroidprime** [comment]
ec_recover for secp256k1 is already implemented by starkware here https://github.com/starkware-libs/cairo-lang/blob/de741b92657f245a50caab99cfaef093152fd8be/src/starkware/cairo/common/cairo_secp/signature.cairo#L181-L213

**Comment by Magicking** [comment]
In addition to help with this issue, there is an example on how to extract (r,s,v) components from a signature from OZ Cairo-contract https://github.com/OpenZeppelin/cairo-contracts/blob/d12abf335f5c778fd19d6f99e91c099b40865deb/src/openzeppelin/account/library.cairo#L140

**Comment by ClementWalter** [comment]
Actually @feltroidprime almost finished it but is stuck with some others projects ; I'll just merge their job tomorrow.

Regarding the link @Magicking , do you know why they use `__fp__`?

**Comment by Magicking** [comment]
Wow did not expect an answer and a fix that fast! Wanted to tackle this as my return to Cairo lang! Anyway Thanks @Eikix & @ClementWalter 

Regarding the modification of `__fp__`, it's usually modified when you have to use an address relative a to local address, see https://starknet.io/docs/reference/syntax.html?highlight=statement#locals & https://starknet.io/docs/how_cairo_works/functions.html#retrieving-registers

**Comment by abdelhamidbakhta** [comment]
> Wow did not expect an answer and a fix that fast! Wanted to tackle this as my return to Cairo lang! Anyway Thanks @Eikix & @ClementWalter
> 
> Regarding the modification of `__fp__`, it's usually modified when you have to use an address relative a to local address, see https://starknet.io/docs/reference/syntax.html?highlight=statement#locals & https://starknet.io/docs/how_cairo_works/functions.html#retrieving-registers

StarkNet builders are not joking, and even more Kakarot ones

**Comment by ClementWalter** [comment]
> Wow did not expect an answer and a fix that fast! Wanted to tackle this as my return to Cairo lang! Anyway Thanks @Eikix & @ClementWalter
> 
> Regarding the modification of `__fp__`, it's usually modified when you have to use an address relative a to local address, see https://starknet.io/docs/reference/syntax.html?highlight=statement#locals & https://starknet.io/docs/how_cairo_works/functions.html#retrieving-registers

yes, but where is it required here? I can't see the need in this code
