### ISSUE TITLE
testing: Review and refactor tests

### ISSUE THREAD

**Issue by 0xMentorNotAPseudo** [sayajin-labs/kakarot#37]
WIP: story to refine but generally speaking - design & refactor tests.

- Integrations tests are missing
- Unit tests and especially `tests/cases` should be reviewed. 

For example, we have `test_arithmetic_operations` which is IMO an integration test by chaining every arithmetic operation into one big operation. Same for `test_duplication_operations`. We can't do the same for `test_comparison_operations`.  

**Suggestion**: the unit test scope of an opcode should be the opcode itself.

We should avoid using `00x.json` as the fixture's name. To allow the factorization of tests, payload of fixture should also accept an array of scenarios instead of just one scenario.

**Comment by Eikix** [comment]
I think @ClementWalter solved this, we should be able to close this issue
