### ISSUE TITLE
dev: Move memory expansion logic to load and store functions

### ISSUE THREAD

**Issue by pedrobergamini** [sayajin-labs/kakarot#371]
I was reading #40 and noticed that memory expansion dynamic gas cost has already been implemented for some opcodes. In order to have it properly applied to other opcodes, I think we should refactor to call `ensure_length` inside `Memory.load` and `Memory.store` to apply the memory expansion cost in any opcode that uses those methods and its related functions such as `load_n` and `store_n` . 

Wanted to have communtiy input to ensure it's a valid assumption, and if not think on a different way of having this logic applied to the other necessary opcodes.

**Comment by pedrobergamini** [comment]
if my assumption is valid I can open a PR for the implementation

**Comment by Eikix** [comment]
This is a great idea:)! 
I'll modify the initial issue's strategy to consider this optimisation. 

I'll close this issue and continue follow up on #40. I'll assign @pedrobergamini on it
