### ISSUE TITLE
doc: add documentation (comment / docs) to the models.cairo file

### ISSUE THREAD

**Issue by Eikix** [sayajin-labs/kakarot#379]
# Feature Request

As proposed by @hurrikaanig -> our models are currently hard to understand. They should be better documented. 
Please add comments around each model to help the onboarding process and codebase clarity effort.

**Comment by Eikix** [comment]
@hurrikaanig is this the issue you proposed to take:)?

**Comment by hurrikaanig** [comment]
> @hurrikaanig is this the issue you proposed to take:)?

Yep has been merged already !

https://github.com/sayajin-labs/kakarot/pull/389
