### ISSUE TITLE
feat: Switch solc compiler for Foundry compiler project-wide

### ISSUE THREAD

**Issue by Eikix** [sayajin-labs/kakarot#381]
# Feature Request

**Describe the Feature Request**

We need more granular handling of the solidity compiler.

For that, we'll use Foundry as the source of truth for EVM bytecode generation.

**Describe Preferred Solution**

Replace solc, 
Replace solc docker scripts,

Install Foundry,
Link foundry compiler with our testing procedure (compilation of .sol files and generation of ABIs / bytecodes)

**Comment by danilowhk** [comment]
I can take this one :)
