### ISSUE TITLE
feat: Dynamic gas accounting for opcode that might trigger memory expansion (Memory.store, Memory.load)

### ISSUE THREAD

**Issue by abdelhamidbakhta** [sayajin-labs/kakarot#40]
# Feature Request

**Describe the Feature Request**

Currently `MSTORE` operation only account for static gas cost (3). It should also take into consideration dynamic gas cost related to memory expansion.

Memory expansion works as explained in this section: https://www.evm.codes/about#memoryexpansion

**Describe Preferred Solution**

Implement gas accounting that compute the dynamic gas cost of MSTORE.

**Related Code**

- `memory_operations`

**Comment by Eikix** [comment]
What remains to be done for this issue?

**Comment by Eikix** [comment]
Adding @pedrobergamini 's nice observation:

> I was reading https://github.com/sayajin-labs/kakarot/issues/40 and noticed that memory expansion dynamic gas cost has already been implemented for some opcodes. In order to have it properly applied to other opcodes, I think we should refactor to call ensure_length inside Memory.load and Memory.store to apply the memory expansion cost in any opcode that uses those methods and their related functions such as load_n and store_n.

> Wanted to have community input to ensure it's a valid assumption, and if not think of a different way of having this logic applied to the other necessary opcodes.

**Comment by Eikix** [comment]
I'll take this one
