### ISSUE TITLE
test: Refactor test fixtures

### ISSUE THREAD

**Issue by matthieuauger** [sayajin-labs/kakarot#411]
The test fixtures are prefixed in their name, initially to ease readability and sorting them in the file tree by their loading order.

![Image](https://user-images.githubusercontent.com/1172099/210599715-c4efce85-23be-495c-ab4b-6e04896544ae.png)

However the prefixes are hard to maintain and to keep up to date with reality. For example, we have 5_blockhashes which contain fixtures loaded before the starknet fixtures.

We are also loading all fixtures in the top conftest.py, consequently even for running a smol unit test we deploy all the contracts of the repo, we’d need to fix this by carefully placing the fixture right where they are required in subfolder’s conftest.py.

We want to : 
- remove the prefix in the test names
-  place the fixtures in the right conftest to optimize test execution time

**Comment by mradolux** [comment]
Hello ! I'd like to take this issue please

**Comment by ptisserand** [comment]
Hi @mradolux , are you still working on this issue?

**Comment by mradolux** [comment]
Hi @ptisserand, I didn't get assigned to it
