### ISSUE TITLE
bug: REVERT does not return the revert reason

### ISSUE THREAD

**Issue by ClementWalter** [sayajin-labs/kakarot#416]
# Bug Report

#f03cf627ff871b5795cf561e84720244cf7eca71

**Current behavior:**

REVERT does not use `size` to load the proper data from memory

**Expected behavior:**

REVERT uses all the popped value to load the right amount of data.

**Steps to reproduce:**

Test against the raised error in `test_system_operations::test_revert`

**Related code:**

```
        // TODO: implement loading of the revert reason based on size value,
        // currently limited by short string size
        let size = popped[0];
        let offset = popped[1];

        // Load revert reason from offset
        let (memory, revert_reason_uint256, gas_cost) = Memory.load(memory, offset.low);
        local revert_reason = revert_reason_uint256.low;

        // revert with loaded revert reason short string
        with_attr error_message("Kakarot: Reverted with reason: {revert_reason}") {
            assert TRUE = FALSE;
        }
```

**Other information:**

I don't know the actual limitation of `with_attr error_message`

**Comment by Eikix** [comment]
Don't forget to update [this assertion](https://github.com/sayajin-labs/kakarot/pull/425/commits/af4b95022c1a9468474e6c655cf6b53234bd9d4e#diff-2f9d340347f24709a738e5782c40e78301ca83034edd6dc065e5e407ed1436fcR92)
