### ISSUE TITLE
bug: Fix usage of SafeMath in arithmetic opcodes

### ISSUE THREAD

**Issue by ClementWalter** [sayajin-labs/kakarot#419]
# Bug Report

**Current behavior:**

The PR https://github.com/sayajin-labs/kakarot/pull/415 fixed usage of `SafeMath` for `ADD` and `MUL`. Some others opcodes still use `SafeMath`.

**Expected behavior:**

The goal of this issue is to find out wether we need to keep them or not by looking at the EVM spec.

**Related code:**

see `src/kakarot/instructions/stop_and_arithmetic_operations.cairo`

**Comment by mradolux** [comment]
Hi ! can I take this issue ?

**Comment by Eikix** [comment]
Sorry it appears @FranFiuba is already working on it
