### ISSUE TITLE
feat: Kakarot Ethereum Account Interface

### ISSUE THREAD

**Issue by Flydexo** [sayajin-labs/kakarot#423]
# Feature Request

The idea is to create a standard for the KETHAA contract with a custom interface Id so other accounts can implement the standard.

**Describe Preferred Solution**

For the moment, the only idea I have is to create a cairo namescape with the constructor, views, externals and storage vars. And data when should be constant.

**Related Code**

No code for the moment

**Additional Context**

The openzeppelin account interface: https://github.com/OpenZeppelin/cairo-contracts/discussions/41

**If the feature request is approved, would you be willing to submit a PR?**
Yes

**Comment by ClementWalter** [comment]
could you please provide a bit more context? When I look at the link you mentioned, the last post is 5 months old and actually defines the interface we're using, precisely:

```
%lang starknet

struct Call {
    to: felt,
    selector: felt,
    calldata_len: felt,
    calldata: felt*,
}

// Tmp struct introduced while we wait for Cairo to support passing `[Call]` to __execute__
struct CallArray {
    to: felt,
    selector: felt,
    data_offset: felt,
    data_len: felt,
}

@contract_interface
namespace IAccount {

    func supportsInterface(interfaceId: felt) -> (success: felt) {
    }

    func isValidSignature(
        hash: felt,
        signature_len: felt,
        signature: felt*
    ) -> (isValid: felt) {
    }

    func __validate__(
        call_array_len: felt,
        call_array: CallArray*,
        calldata_len: felt,
        calldata: felt*
    ) {
    }

    func __validate_declare__(class_hash: felt) {
    }

    func __execute__(
        call_array_len: felt,
        call_array: CallArray*,
        calldata_len: felt,
         calldata: felt*
    ) -> (response_len: felt, response: felt*) {
    }
}

```

**Comment by ClementWalter** [comment]
I am wondering if we could have a single Account contract that could be used by both Starknet and EVM wallets. However, since the forthcoming decisions about where kakarot will live (L2, L3, substrate) are open and will strongly impact this part of the stack, I'd recommend not to spend to much time on this rn

**Comment by Eikix** [comment]
Closing this, as #498 fixes it
