### ISSUE TITLE
feat: add testing to the Precompiles namespace

### ISSUE THREAD

**Issue by jobez** [sayajin-labs/kakarot#424]
# Feature Request

**Describe the Feature Request**

We want to more fully test the Precompiles namespace.

**Describe Preferred Solution**

Update the tests as follows:

- `run`:
    - use `dataCopy` as we cannot mock `_exec_precompile`
    - test that the returned ExecutionContext is consistent
- `is_precompile`:
    - test returns TRUE/FALSE appropriately
- `not_implemented_precompile`
    - test raises with appropriate error message
- `_exec_precompile`
    - update existing test for `run` and make it an `_exec_precompile` one. Test for a not implemented precompile instead (current test is wrong as it doesn't use an address in the range <= last_precompile_address)

Expected python structure in `test_precompile.py` is:

```
class TestPrecompiles:

    class TestRun:
    class TestIsPrecompile:
    class TestNotImplementedPrecompile:
    class TestExecPrecompile:
```

**Related Code**

`precompiles.cairo`,  `test_precompiles.cairo` & `test_precompiles.py`

**Comment by FranFiuba** [comment]
I would take this one.
