### ISSUE TITLE
bug: the EVM address of a deployed contract is wrong

### ISSUE THREAD

**Issue by ClementWalter** [sayajin-labs/kakarot#426]
# Bug Report

**Current behavior:**

The EVM address of a contract account is computed as follows:

```
        // Generate EVM_contract address from the new cairo contract
        // TODO: Use RLP to compute proper EVM address, see https://www.evm.codes/#f0
        let (_, low) = split_felt(starknet_contract_address);
        local evm_contract_address = 0xAbdE100700000000000000000000000000000000 + low;
```

**Expected behavior:**

Depending on wether the call is a `CREATE` or a `CREATE2`, the address should be computed with

- CREATE (see https://www.evm.codes/#f0)
```
address = keccak256(rlp([sender_address,sender_nonce]))[12:]
```
- CREATE2 (see https://www.evm.codes/#f5)
```
address = keccak256(0xff + sender_address + salt + keccak256(initialisation_code))[12:]
```

**Related code:**

See `ContractAccount.deploy` function.
RLP utils are added in https://github.com/sayajin-labs/kakarot/pull/422

**Comment by jobez** [comment]
Deployment in the case of the create2 opcode is addressed in a PR currently under review. Once that is approved, I will be working on the create opcode next.
