### ISSUE TITLE
feat: Add gas_used to kakarot.execute_at_address returned values

### ISSUE THREAD

**Issue by ClementWalter** [sayajin-labs/kakarot#428]
# Feature Request

**Describe the Feature Request**

The `gas_used` field of the `ExecutionContext.summary` is not returned by `kakarot.execute_at_address`.

**Describe Preferred Solution**

Just add it to the function signature and return the `summary.gas_used` value.

**Related Code**

`kakarot.cairo::execute_at_address`

Note:

Returning the gas used for the solidity based tests requires to update the `wrap_zk_evm` decorator, see https://github.com/sayajin-labs/kakarot/blob/5a077535279dbdbdb6b22bf05df45d2a522a0441/tests/integration/helpers/wrap_kakarot.py#L59

The `gas_usage` should be retrieved from the `res` variable and returned as well. For the sake of brevity the wrapper currently only returns the returned data and not the tx. Consequently we need to update this in one way or another to add this info.

Few options are:
- returning the tx when calling `execute`
  - as a tuple: `returned_data, tx = await contract.execute(...)`
  - only the `tx = await contract.execute(...)` and adding the retuned data in the tx
- add a `tx` attribute to the contract like the `events` and set it to the return `res`: `setattr(contract, "tx", res)`

I'd go for the last one to keep it simple when one doesn't need this extra data (the majority of cases), but of course open to discussion.

**Comment by mradolux** [comment]
Hello, I'd like to take this issue

**Comment by ClementWalter** [comment]
just assigned you, feel free to ask any question to help you with the issue
