### ISSUE TITLE
bug: REVERT should not stop execution in sub context

### ISSUE THREAD

**Issue by ClementWalter** [sayajin-labs/kakarot#432]
# Bug Report

**Current behavior:**

The `REVERT` opcode reverts the whole starknet transaction.

**Expected behavior:**

As per the doc:

> Stop the current context execution, revert the state changes (see [STATICCALL](https://www.evm.codes/#FA) for a list of state changing opcodes) and return the unused gas to the caller. It also reverts the gas refund to its value before the current context. If the execution is stopped with REVERT, the value 0 is put on the stack of the calling context, which continues to execute normally. The [return data](https://www.evm.codes/about) of the calling context is set as the given chunk of memory of this context.

**Related code:**

`exec_revert` opcode.

**Other information:**

The list of opcodes modifying the state is:  CREATE, CREATE2, LOG0, LOG1, LOG2, LOG3, LOG4, SSTORE, SELFDESTRUCT.

A possible strategy could be:
- add in the `ExecutionContext` keys for storing `LOG_i` (events) to be emitted and emit only when context is stopped
- add in the `ExecutionContext` a `dict` of all updated storage and revert them if ctx fails.
- add in the `ExecutionContext` a `list` of addresses created with CREATE/CREATE2 and use the same logic as `exec_selfdestruct` if ctx fails.

**Comment by jobez** [comment]
I can work on this 🦫

**Comment by ClementWalter** [comment]
@jobez I expect this issue to have unexpected difficulties, I drafted a possible implementation but there may be flaws in it!
