### ISSUE TITLE
bug: require(address != 0) does not work for address == 2**128

### ISSUE THREAD

**Issue by ClementWalter** [sayajin-labs/kakarot#439]
# Bug Report

**Current behavior:**

Fix the test marked as `skip` in `test_plain_opcodes::TestRequire`

**Expected behavior:**

Test passes unskipped

**Steps to reproduce:**

Run the test

**Other information:**

I have only tested cases with `_address = 1 << 4*i`, ie one single nibble, and it failed from `2**128`. I don't know the behaviour when `_address` has both `low != 0` & `high != 0`

**Comment by jobez** [comment]
i'll be working on this 🛠️
