### ISSUE TITLE
feat: (EOA) Transaction execution

### ISSUE THREAD

**Issue by Flydexo** [sayajin-labs/kakarot#442]
# Feature Request

**Describe the Feature Request**

The EOAccount currently only validates the transaction in `__validate__`. We now need to actually call kakarot in the `__execute__`.

**Describe Preferred Solution**

At the end of the `__execute__` function call the kakarot contract with the calldata previously validated by the `__validate__` function.

**Related Code**

Solving this issue requires to:
- add an `execute` function in the `src/kakarot/accounts/eoa/aa/library.cairo` library (path may have changed to `src/kakarot/accounts/eoa/library.cairo` depending on https://github.com/sayajin-labs/kakarot/issues/445
- call this function in the corresponding `src/kakarot/accounts/eoa/aa/externally_owned_account.cairo` contract

You can take inspiration from @Flydexo own repo:
- https://github.com/Flydexo/kakarot/blob/ce1c8b8528e6b3423923facb3806e08a90723615/src/kakarot/accounts/eoa/aa/externally_owned_account.cairo#L100
- https://github.com/Flydexo/kakarot/blob/ce1c8b8528e6b3423923facb3806e08a90723615/src/kakarot/accounts/eoa/aa/library.cairo#L272

See also other (regular) implementations:
- [OpenZeppelin](https://github.com/OpenZeppelin/cairo-contracts/blob/70cbd05ed24ccd147f24b18c638dbd6e7fea88bb/src/openzeppelin/account/library.cairo#L177)
- [ArgentX](https://github.com/argentlabs/argent-contracts-starknet/blob/3e31c25843010149027ca1bdce251b8d63bdfd9c/contracts/account/ArgentAccount.cairo#L101)

**Comment by Flydexo** [comment]
Started work here: https://github.com/Flydexo/kakarot/tree/feat/legacy

**Comment by TotalPizza** [comment]
Taking over task for TLV Hackathon
