### ISSUE TITLE
bug: ORIGIN returns 0 for EOAccount

### ISSUE THREAD

**Issue by ClementWalter** [sayajin-labs/kakarot#445]
# Bug Report

**Current behavior:**

The `ORIGIN` opcode looks for the EVM address of the tx initiator in the `Registry`. However the EthAA Account do not use this registry, hence the opcode returns 0.

**Expected behavior:**

Returns the EVM address

**Steps to reproduce:**

See test `PlainOpcodes.originAndSender`.

**Related code:**

`exec_origin`, `account_registry` and `contract_account`.

To fix this:
- remove the `AccountRegistry`
- add a `get_evm_address` in the `ContractAccount` as in the `EthAA`
- create an interface `IAccount` that defines this function only
- use `IAccount.get_evm_address` in ORIGIN and in CALLER

# EDIT

A deeper review of this issue leads to the following changes:

- the `deployer` contract is moved one level up
- the `registry/account` is removed
- the `registry/blockhash` is moved one level up
- the `ContractAccount` should mimic the `EAO` account:
  - constructor takes `kakarot_address, evm_address` and no more `bytecode`
  - add a `func get_eth_address` to the `ContractAccount`
- in the `deployer`:
  - remove `@external` from `create_account`
  - add `create_externally_owner_account` and `create_contract_account` that call `create_account`
  - `create_contract_account` is what was in `ContractAccount.library.deploy`
  - add a `CA_VERSION` to be set to the id of the current `ContractAccount` interface (see `get_interface_id`)
  - rename `AA_VERSION` into `EAO_VERSION`
  - similarly to `create_account`, update `compute_starknet_address` to be used by the two new `compute_eoa_starknet_address` and `compute_ca_starknet_address`
- move all constants like `@storage_var kakarot_address` to `kakarot.constants`
- the, update `CALLER` and `ORIGIN` to use the same `IAccount.get_eth_address` whatever the starknet address is

**Comment by hurrikaanig** [comment]
May I take this :)
