### ISSUE TITLE
bug: RETURNDATACOPY fails in PlainOpcode test

### ISSUE THREAD

**Issue by ClementWalter** [sayajin-labs/kakarot#446]
# Bug Report

**Current behavior:**

Test `PlainOpcodes::test_should_return_owner_as_origin_and_caller_as_sender` raises an error in RETURNDATACOPY.

**Expected behavior:**

Test passes

**Steps to reproduce:**

Run test

**Other information:**

Upon fixing the RETURNDATACOPY, the assert in the test should be updated to check that the `data` is correct

**Comment by seshanthS** [comment]
I would like to be assigned to this issue .
