### ISSUE TITLE
bug: CALLER returns same address in sub_context

### ISSUE THREAD

**Issue by seshanthS** [sayajin-labs/kakarot#452]
# Bug Report

**Kakarot version:**

**Current behavior:**
`CALLER` (msg.sender) returns the EVM address of transaction initiator in sub-contexts.

EOA -> Contract_A -> Contract_B
`msg.sender` in Contract_B returns EOA

**Expected behavior:**
I. `CALLER` should return EVM address of transaction initiator when root_context is the calling_context.

II. `CALLER` should return the calling context's `evm_contract_address` when, 
1. The calling context is **NOT** the root context
2. The sub_context is **NOT** created as a result of `DELEGATECALL`

**Steps to reproduce:**
See test `PlainOpcodes.originAndSender`.

**Related code:**

[environmental_information.cairo#L165](https://github.com/sayajin-labs/kakarot/blob/main/src/kakarot/instructions/environmental_information.cairo#L165)

**Other information:**

`ctx.calling_context.evm_contract_address` - To get the calling context's evm_address

**Comment by mradolux** [comment]
Hello ! Can I take this one please ?

**Comment by ClementWalter** [comment]
@mradolux sure!
can you plz also fix https://github.com/sayajin-labs/kakarot/pull/449 before actually starting to work on this?

**Comment by mradolux** [comment]
yes of course !
