### ISSUE TITLE
dev: Normalize natspec comments and use them to generate docs from said natspec comments

### ISSUE THREAD

**Issue by jobez** [sayajin-labs/kakarot#458]
# Dev Request

**Describe the Dev Request**

Leverage and normalize natspec comments to have docs generated in the CI

We have non-uniform natspec comments in the codebase. For example:

https://github.com/sayajin-labs/kakarot/blob/74890cb0aa78380cdc484224ffbe4d8739a44e74/src/kakarot/stack.cairo#L55

in contrast with:

https://github.com/sayajin-labs/kakarot/blob/74890cb0aa78380cdc484224ffbe4d8739a44e74/src/utils/utils.cairo#L62

**Describe Preferred Solution**

-  normalize natspec docstrings
- do the integration work on Kakarot to add doc generation and publishing as part of the CI, using https://github.com/onlydustxyz/kaaper

**Comment by Bal7hazar** [comment]
Hey, I did a [first shoot](https://bal7hazar.github.io/kakarot/), minor things to fix in the doc, but I'll stop for today.

Could you tell me if it match what you expect before I commit more on it?

Note:
- I didn't work on natspec comments for now
- I did the hosting manually, I need to dig a big more to manage the deploy through the CI. About this point, I was wondering if you wanted to host the react doc in this repo, an alternative could be to host the doc in another repo and "bind" CI to deploy the doc from the new repo when an event is send in this repo. It could be much more work but it could keep this repo cleaner.

**Comment by Eikix** [comment]
What is the status of this? Should we close the issue @Bal7hazar ?

**Comment by Bal7hazar** [comment]
@Eikix it was not finish :sweat: 

I needed this [PR](https://github.com/onlydustxyz/kaaper/pull/49) to be merged to start working on Kakarot natspec comments (clean things, etc.)

I'll try to finish it this week.

**Comment by Eikix** [comment]
> @Eikix it was not finished :sweat: 
> 
> I needed this [PR](https://github.com/onlydustxyz/kaaper/pull/49) to be merged to start working on Kakarot natspec comments (clean things, etc.)
> 
> I'll try to finish it this week.

Do you know if natspecs or similar stuff will be kept for Cairo1 I would want your hard work to live long 🫡🤝

**Comment by Bal7hazar** [comment]
> Do you know if natspecs or similar stuff will be kept for Cairo1 I would want your hard work to live long 🫡handshake

We will defintely need to upgrade kaaper to be Cairo 1.0 compatbile. It will also be a good opportunity to check if rust compatible doc generators do the job (then we could cancel Kaaper).

**Comment by Bal7hazar** [comment]
```cairo
func exec_stop{
        syscall_ptr: felt*,
        pedersen_ptr: HashBuiltin*,
        range_check_ptr,
        bitwise_ptr: BitwiseBuiltin*,
    }(ctx_ptr: model.ExecutionContext*) -> model.ExecutionContext* {
        let ctx = ExecutionContext.stop(ctx_ptr);
        return ctx;
    }
```

These function are not parsed correctly by kaaper due to return format.

Options:
- Take time to fix it in kaaper, then finalize the issue.
- Ignore it, so all these functions will be ignored by kaaper and won't be inculded in the final documentation (until Cairo 1.0 I guess).
@Eikix
