### ISSUE TITLE
dev: Benchmark and select a package manager for kakarot

### ISSUE THREAD

**Issue by ClementWalter** [sayajin-labs/kakarot#460]
Long story short:
- the project happened to use protostar
- we eventually removed it as it was used mainly for testing, and not so useful
- we now with precompile have copy/pasted quite a bit of code from external lib/repo
- we need to fix this to have in our codebase only code that we wrote and libs as _libs_

Requirements: the selected method needs to be able to handle any kind of repo:
- python packages (with setup.py/pyproject.toml)
- protostar packages
- felucca packages
- plain cairo repo (no packaging, only cairo files + README)

Possible solutions to investigat:
- re-use `protostar`
- use `git submodules` by hand
- use `forge install` (similar to previous command)
- use https://docs.apeworx.io/
- use https://github.com/franalgaba/felucca
- suggest something!

**Comment by ftupas** [comment]
Hello there, may I take this one? I'm on vacation right now until Feb 17 but will try to do some partial work on some days. Otherwise if anyone wants to take it, please feel free to re-assign 🙂

**Comment by ftupas** [comment]
Got it, thanks! 👍
