### ISSUE TITLE
bug: gas metering is inaccurate in kakarot

### ISSUE THREAD

**Issue by mradolux** [sayajin-labs/kakarot#461]
# Bug Report

**Kakarot version:**

**Current behavior:**

Gas metering is innacurate in kakarot. Test skipped because the 'gas_used' variable doesn't match with the `gas_used` variable tested by UniswapV2 : '2512920'

**Expected behavior:**

Test should pass with correct `factory.tx.result.gas_used` variable which must be equal to '2512920'

**Related code:**

[UniswapV2/test_uniswap_v2_factory.py#L75](https://github.com/sayajin-labs/kakarot/blob/fe03ff003c0f04b96a02572899ca6c8a8e613e0a/tests/integration/solidity_contracts/UniswapV2/test_uniswap_v2_factory.py#L75)

**Other information:**

'factory.tx.result.gas_used' in the test is currently higher than expected

**Comment by mradolux** [comment]
Hi, yes I'll add the gas_used result that kakarot is returning, and can I please get assigned to this issue to fix it ?

**Comment by Eikix** [comment]
I believe we shouldn't take too much time now, as after the cairo1 migration we'll stop doing gas metering from inside our applicative code, none of the gas computation logic will be migrated
