### ISSUE TITLE
feat: Allow Kakarot to spend infinite amount for (EO/Contract)Accounts

### ISSUE THREAD

**Issue by ClementWalter** [sayajin-labs/kakarot#464]
# Feature Request

**Describe the Feature Request**

Kakarot contract has to transfer funds in `CALL` opcode. To do so, it will call `IERC20.transferFrom` and consequently need to be approved.

**Describe Preferred Solution**

Upon deployment of the (EO/Contract)Account, in the constructor, use `IERC20.approve` to approve kakarot for an infinite amount (`=Uint(2**128-1, 2**128-1)` , see `ERC20.cairo`)

- add a `get_native_token` to Kakarot interface and contract
- create a `constructor` method in the eoa library
- move code from `externally_owned_account.cairo` to this `constructor`
- get Kakarot `native_token_address` : `IKakarot.get_native_token(kakarot_address)`
- use this address to give inifinite allowance to kakarot:

```
let (infinite: Uint256) = uint256_not(Uint256(0, 0));
IERC20.approve(native_token_address, kakarot_address, infinite);
```

- do the same for the `contract_account.cairo`

**Related Code**

https://github.com/sayajin-labs/kakarot/blob/de197043c168f57f3e598a62cd363d7599c2d3bd/src/kakarot/accounts/eoa/aa/externally_owned_account.cairo#L28
https://github.com/sayajin-labs/kakarot/blob/de197043c168f57f3e598a62cd363d7599c2d3bd/src/kakarot/accounts/contract/library.cairo#L58

**Comment by greged93** [comment]
Hey @ClementWalter, I'm down to work on this if possible :)

**Comment by ClementWalter** [comment]
@greged93 #498 has been merged so you can work on this!

**Comment by TotalPizza** [comment]
@greged93
This wasn't worked on at the hackathon.
So you can take up the task again if you want :)

**Comment by ClementWalter** [comment]
@TotalPizza @greged93 so there're actually 3 issues required for univ2, this one and
- https://github.com/sayajin-labs/kakarot/issues/466
- https://github.com/sayajin-labs/kakarot/issues/465

that need to ne done AFTER this.

So you can probably share the work if you feel so. I know that @greged93 won't be able to do anything before this weekend so @TotalPizza if you can, maybe you can tackle this one before the weekend and leave the others / one of the others to greg?

**Comment by ClementWalter** [comment]
note also that the possible implementation may be a little bit outdated since it was written before the massive refacto of the contact, though it is still understandable I guess. happy to help if required

**Comment by greged93** [comment]
I can take on one of #465 or #466 if it helps speed up and leave this one to @TotalPizza, fine for me!

**Comment by TotalPizza** [comment]
Okidoki I'll take #464 then :)
