### ISSUE TITLE
feat: Transfer token in CALL

### ISSUE THREAD

**Issue by ClementWalter** [sayajin-labs/kakarot#465]
# Feature Request

**Describe the Feature Request**

When using the `CALL` opcode, `value` should be transferred to the target contract.

**Describe Preferred Solution**

Add a `IERC.transfer` in the `exec_call` opcode here https://github.com/sayajin-labs/kakarot/blob/de197043c168f57f3e598a62cd363d7599c2d3bd/src/kakarot/instructions/system_operations.cairo#L259

 - import `native_token_address` from `kakarot/constants.py`
 - call `IERC20.transferFrom(native_token_address, ctx.starknet_contract_address, sub_ctx.starknet_contract_address, sub_ctx.value);

**Comment by FranFiuba** [comment]
taking this because #466 is blocked

**Comment by ClementWalter** [comment]
@FranFiuba #498 has been merged so you can work on this!

**Comment by greged93** [comment]
Can hop on this one once #466 is merged (if it's free :))
