### ISSUE TITLE
feat: Transfer token in EOA

### ISSUE THREAD

**Issue by ClementWalter** [sayajin-labs/kakarot#466]
# Feature Request

**Describe the Feature Request**

When a user (an EOA) sends a transaction with value, we need to send this value...

**Describe Preferred Solution**

The entrypoint of an EOA triggered tx is the `__execute__` function of the EOA contract.

- get kakarot native token address `IKakarot.get_native_token`
- get value to be send in tx field, and tx target
- call `IERC20.transfer(native_token_address, target, value)`

**Related Code**

This issue needs to be tackled after https://github.com/sayajin-labs/kakarot/issues/442 is merged

**Comment by FranFiuba** [comment]
I will take this one.

**Comment by ClementWalter** [comment]
> I will take this one.

you'd need to wait for the #442 before being able to work on this

**Comment by ClementWalter** [comment]
@FranFiuba #498 has been merged so you can work on this!

**Comment by greged93** [comment]
Is this one free ? If so I can take it :)
