### ISSUE TITLE
feat: test compute_starknet_address

### ISSUE THREAD

**Issue by hurrikaanig** [sayajin-labs/kakarot#477]
# Feature Request

**Describe the Feature Request**

Provide a unit test for `compute_starknet_address` in `accounts.library`

**Describe Preferred Solution**

Test should be made in `unit.src.kakarot.accounts`.

Create a `test_accounts.cairo` where you import `compute_starknet_address` from `kakarot.accounts.library` and test it in `test_accounts.py`. You could compare our function returned value to the one returned by starkware python lib.

**Comment by Eikix** [comment]
@izzetemredemir will take it

**Comment by izzetemredemir** [comment]
Hey, I can look this issue

**Comment by ClementWalter** [comment]
@izzetemredemir any update on this?

**Comment by izzetemredemir** [comment]
Sorry for the late update. I am not able to do it now.

**Comment by dragan2234** [comment]
hey I could take this, have some ideas on how to do it

**Comment by dragan2234** [comment]
@ClementWalter can you please assign me to this task
