### ISSUE TITLE
feat: modify CA_VERSION in constants

### ISSUE THREAD

**Issue by hurrikaanig** [sayajin-labs/kakarot#481]
# Feature Request

Modify CA_VERSION value using pedersen_hash of "KAKAROT_CA_V0.0.1" and replace EOA_VERSION value by pedersen hash of "KAKAROT_EOA_V0.0.1" (instead of "KAKAROT_AA_V0.0.1")

**Related Code**

`constants.cairo`

**Comment by karasakalmt** [comment]
Can i take it?

**Comment by ClementWalter** [comment]
any update on this?
