### ISSUE TITLE
feat: add deploy support in EOA / Kakarot

### ISSUE THREAD

**Issue by Eikix** [sayajin-labs/kakarot#491]
# Feature Request

Deploy is done in EVM by sending a raw transaction to address "empty string" 
And calldata := bytecode! 

EOA needs to handle this case. 
Idea: by branching ifs on the `to` field inside the transaction (e.g. if to if empty string -> kakarot.deploy, else kakarot.execute_at_address)

**Comment by TotalPizza** [comment]
I'd take this one :)
Would just wait for the actual implementation of __execute__ to be merged into main.
