### ISSUE TITLE
feat: use individual contract nonces

### ISSUE THREAD

**Issue by TotalPizza** [sayajin-labs/kakarot#505]
# Feature Request

**Describe the Feature Request**

Currently new contract_accounts are deployed using the kakarot `salt` which is a global nonce that is being incremented for every deployed contract.
By tracking an individual nonce for each contract_account and eoa, the deployed contract will have the same address as they would on ethereum.

**Describe Preferred Solution**

For the eoa it might be viable to use the nonce provided by starknet (which can accessed via the syscall `get_tx_info`).
That way we save storage costs.
Kakarot RPC can fetch the nonce via the Starknet cli.
But for the Create and Create2 opcodes we require the nonces of the contract_account that holds the respective opcodes. 
Therefore I'd suggest adding a `nonce` storage var, as well as a `@view` and `increment` method.

**Describe Alternatives**

Alternatively we can let the current nonce system be. It's not a big blocker as far as I can tell.
It's just another (imo important) step to EVM compatibility. It would enable DAOs to have the same address for their DAPP or multisig as on every other EVM chain.

**If the feature request is approved, would you be willing to submit a PR?**
Yes

**Comment by Eikix** [comment]
Do we know how this will be handled in Cairo 1 ?

**Comment by Eikix** [comment]
When a smart contract deploys another smart contract in Ethereum, using CREATE or CREATE2, what nonce is used?
The smart contract's nonce or the EOA's ?

**Comment by TotalPizza** [comment]
> 

By the contract, according to:
https://ethereum.org/en/developers/docs/accounts/
And also the yellow paper and some EIPs that are related like:
https://github.com/ethereum/EIPs/blob/master/EIPS/eip-161.md

contract accounts nonces are only used for contract creations i.e. CREATE.
EOA nonces are incremented for transactions and contract deployments.

**Comment by TotalPizza** [comment]
> Do we know how this will be handled in Cairo 1 ?

No idea, I can start digging tho.
Have not heard about any changes in that regard.

**Comment by TotalPizza** [comment]
Once kakarot moves away from Starknet, it will have to handle nonces itself anyways.
So maybe it makes sense to not rely on Starknet syscalls, even if that leads to a redundancy in the short term.

**Comment by ClementWalter** [comment]
This (starknet nonce of EOA and `nonce` storage var for CA) seems reasonable to me.

**Comment by Eikix** [comment]
Seems reasonable as well to me
