### ISSUE TITLE
Workshop:  Remove unneeded code

### ISSUE THREAD

**Issue by TotalPizza** [sayajin-labs/kakarot#513]
Level: Medium

The following function currently spans 10 lines.
However, it includes some unneeded code that, if removed, would reduce the number of lines to 8.
https://github.com/sayajin-labs/kakarot/blob/286aaea710b22bf78facd5257a9da4b608e68a6e/src/kakarot/accounts/contract/library.cairo#L94-L103

You could reduce the line count to 7 by making changes to the type that is being returned.
Your final implementation should at least remove the all unneeded code.

**Comment by sarantapodarousa** [comment]
Hi, can you please let me try this one ?

**Comment by ClementWalter** [comment]
Sure, plz don’t hesitate should you have any questions !
