### ISSUE TITLE
Workshop: Remove unused function

### ISSUE THREAD

**Issue by TotalPizza** [sayajin-labs/kakarot#514]
Level: Easy

The proxy contract used for contract accounts and EOAs contains a function that is not needed.
`src/kakarot/accounts/proxy/proxy.cairo`

Remove the unused function.

**Comment by 0xKarasu** [comment]
Can I take this one ?

The view function `get_implementation` looks useless there.

**Comment by TotalPizza** [comment]
Sure you can, however we'd prefer to keep `get_implementation`. :)
(As it is practical to read the class hash once the contract is deployed)
I was thinking more about the `Constructor`.

**Comment by 0xKarasu** [comment]
> Sure you can, however we'd prefer to keep `get_implementation`. :) (As it is practical to read the class hash once the contract is deployed) I was thinking more about the `Constructor`.

That was my initial guess but now I'm confused, why do you use an initializer even for the proxy ?

(also, I'm not sur that you check that the proxy initializer is only called once)
