### ISSUE TITLE
Workshop: Booleans in Cairo

### ISSUE THREAD

**Issue by TotalPizza** [sayajin-labs/kakarot#517]
Level: Easy

As Cairo doesn't have a native boolean type, it is not uncommon to see developers using 0 and 1 as a replacement.
E.g. 
```
if (result == 0):
    //Do Something
```
However, for readability purposes we prefer to utilize the FALSE and TRUE constants from the common cairo-lang library:
https://github.com/starkware-libs/cairo-lang/blob/master/src/starkware/cairo/common/bool.cairo

In the following file 1 is still used instead of the TRUE constant.
https://github.com/sayajin-labs/kakarot/blob/f519876a3acb67507ccea05e1f87d82f36093142/src/utils/utils.cairo#L257-L260

To fix this import the relevant cairo-lang library and replace 1 with the TRUE constant.

**Comment by weiihann** [comment]
Hello! Can I take this?

**Comment by TotalPizza** [comment]
Sure, go ahead :)
