### ISSUE TITLE
feat: implement 0x5b - JUMPDEST 

### ISSUE THREAD

**Issue by Eikix** [sayajin-labs/kakarot#69]
### Since

Frontier

### Group

Stack, Memory, Storage and Flow Operations

### Description

0x5b - JUMPDEST 

<br class="Apple-interchange-newline">Mark a valid destination for [JUMP](https://www.evm.codes/#56) or [JUMPI](https://www.evm.codes/#57). This operation has no effect on machine state during execution.

**Comment by danilowhk** [comment]
I can do this one
