### ISSUE TITLE
feat: implement 0x57 - JUMPI

### ISSUE THREAD

**Issue by Eikix** [sayajin-labs/kakarot#80]
### Since

Frontier

### Group

Stack, Memory, Storage and Flow Operations

### Description

0x57 - JUMPI

Index 1 is top of the stack. See [PUSH](https://www.evm.codes/#60).

Notes
The program counter (PC) is a byte offset in the deployed [code](https://www.evm.codes/about). It indicates which instruction will be executed next. When an [ADD](https://www.evm.codes/#01) is executed, for example, the PC is incremented by 1, since the instruction is 1 byte. The [PUSH](https://www.evm.codes/#60) instructions are bigger than one byte, and so will increment the counter accordingly.

The JUMPI instruction may alter the program counter, thus breaking the linear path of the execution to another point in the deployed [code](https://www.evm.codes/about). It is used to implement functionalities like loops and conditions.

Stack input
counter: byte offset in the deployed [code](https://www.evm.codes/about) where execution will continue from. Must be a [JUMPDEST](https://www.evm.codes/#5B) instruction.
b: the program counter will be altered with the new value only if this value is different from 0. Otherwise, the program counter is simply incremented and the next instruction will be executed.
Example
[See in playground](https://www.evm.codes/playground?unit=Wei&codeType=Mnemonic&code=%27qFirstk%20noYjump%2C%20secondkw0%20XRY0w10z2~h4~W_z5w12z7~h9~Z0gINVALIDK11gZ2w_z13%27~%20%7Bprevious%20instruction%20occupiR%202%20bytR%7DgzXseYwgWq%2F%2F%20k%20example%20doRhQI%20%20Kg%5Cn_1%20ZQDESTz1Yt%20X%20qOffWPUSH_ResQJUMPK%20z%01KQRWXYZ_ghkqwz~_).

Error cases
The state changes done by the current context are [reverted](https://www.evm.codes/?fork=grayGlacier#FD) in those cases:

Not enough gas.
Not enough values on the stack.
Counter offset is not a [JUMPDEST](https://www.evm.codes/#5B). The error is generated only if the JUMP would have been done.

**Comment by TotalPizza** [comment]
I would also like to work on this one. :)
