### ISSUE TITLE
feat: implement 0x56 - JUMP

### ISSUE THREAD

**Issue by Eikix** [sayajin-labs/kakarot#81]
### Since

Frontier

### Group

Stack, Memory, Storage and Flow Operations

### Description

0x56 - JUMP

Index 1 is top of the stack. See [PUSH](https://www.evm.codes/#60).

Notes
The program counter (PC) is a byte offset in the deployed [code](https://www.evm.codes/about). It indicates which instruction will be executed next. When an [ADD](https://www.evm.codes/#01) is executed, for example, the PC is incremented by 1, since the instruction is 1 byte. The [PUSH](https://www.evm.codes/#60) instructions are bigger than one byte, and so will increment the counter accordingly.

The JUMP instruction alters the program counter, thus breaking the linear path of the execution to another point in the deployed [code](https://www.evm.codes/about). It is used to implement functionalities like functions.

Stack input
counter: byte offset in the deployed [code](https://www.evm.codes/about) where execution will continue from. Must be a [JUMPDEST](https://www.evm.codes/#5B) instruction.
Example
[See in playground](https://www.evm.codes/playground?unit=Wei&codeType=Mnemonic&code=%27wWZjump%20overqinvalid%20and%20jusXgoYoqpushk4x0_%20%20%20x2%20%7Bprevious%20instruction%20occupies%202%20bytes%7DzINVALIDx3_DEST~4k1x5%27~%20wOffseXz%5Cnx%20~w%2F%2F%20qYhZkzPUSH1%20_zJUMPZe%20Y%20tXt%20%01XYZ_kqwxz~_).

Error cases
The state changes done by the current context are [reverted](https://www.evm.codes/?fork=grayGlacier#FD) in those cases:

Not enough gas.
Not enough values on the stack.
Counter offset is not a [JUMPDEST](https://www.evm.codes/#5B). The error is generated even if the JUMP would not have been done.

**Comment by TotalPizza** [comment]
I'd like to take this one. :)
It relies on JUMPDEST to be finished, but I can start building and create the PR once JUMPDEST is completed by danilowhk.
