### ISSUE TITLE
feat: implement 0x3f - EXTCODEHASH

### ISSUE THREAD

**Issue by Eikix** [sayajin-labs/kakarot#92]
### Since

Frontier

### Group

Environmental Information

### Description

0x3f - EXTCODEHASH

<div class="flex-1 lg:pr-8"><p class="leading-5 mb-4"><em>Index 1 is top of the stack. See <a class="underline" href="/#60">PUSH</a>.</em></p><h2 class="text-base font-semibold my-4">Stack input</h2><ol class="list-decimal mb-4"><li class="ml-6"><code>address</code>: 20-byte address of the account.</li></ol><h2 class="text-base font-semibold my-4">Stack output</h2><ol class="list-decimal mb-4"><li class="ml-6"><code>hash</code>: hash of the chosen account's <a class="underline" href="/about">code</a>, the empty hash (0xc5d24601...) if the account has no <a class="underline" href="/about">code</a>, or 0 if the account does not exist or has been destroyed.</li></ol><h2 class="text-base font-semibold my-4">Examples</h2><table class="table-auto mb-4"><thead><tr><th class="py-1 px-2 border-indigo-200 dark:border-black-400 text-gray-800 dark:text-gray-400 text-tiny font-medium break-all"></th><th class="py-1 px-2 border-indigo-200 dark:border-black-400 text-gray-800 dark:text-gray-400 text-tiny font-medium break-all border">Input</th><th class="py-1 px-2 border-indigo-200 dark:border-black-400 text-gray-800 dark:text-gray-400 text-tiny font-medium break-all border">Output</th></tr></thead><tbody><tr><td class="py-1 px-2 border-indigo-200 dark:border-black-400 text-tiny font-normal break-all border"><code>1</code></td><td class="py-1 px-2 border-indigo-200 dark:border-black-400 text-tiny font-normal break-all border"><code>0x43a61f3f4c73ea0d444c5c1c1a8544067a86219b</code></td><td class="py-1 px-2 border-indigo-200 dark:border-black-400 text-tiny font-normal break-all border"><code>0xc5d2460186f7233c927e7db2dcc703c0e500b653ca82273b7bfad8045d85a470</code></td></tr></tbody></table><p class="leading-5 mb-4"><a class="underline" href="/playground?unit=Wei&amp;codeType=Mnemonic&amp;code=%27yClmthaWcl_%204%20FFZjYdeg3%200x63FFFFFFFF60005260046000F3q0~MSTORE~~yCfz_zmYdeZboveq13q0q0~CREATE%20yPutsznewVaddresjonzstack~~yGetzhash~EXTCODEHASH%27~%5Cnz%20the%20y%2F%2F%20qgVYntracWmYnstructor%20lfja%20js%20g~PUSH1freate_pwithZ%20aYcoWt%20V%20p%01VWYZ_fgjlmpqyz~_">Reproduce in playground</a></p><h2 class="text-base font-semibold my-4">Error cases</h2><p class="leading-5 mb-4">The state changes done by the current context are <a class="underline" href="/?fork=grayGlacier#FD">reverted</a> in those cases:</p><ul class="list-disc mb-2"><li class="ml-6">Not enough gas.</li><li class="ml-6">Not enough values on the stack.</li></ul><h2 class="text-base font-semibold my-4">Gas</h2><p class="leading-5 mb-4">The static cost is 0. If the accessed address is warm, the dynamic cost is 100. Otherwise the dynamic cost is 2600. See section <a class="underline" href="/about">access sets</a>.</p></div>

### Possible implementation

1. `contract_account.bytecode()` to retrieve the code of the given contract
2. take inspiration from SHA3 to compute the hash of the `bytecode_len, bytecode` array.

**Comment by Eikix** [comment]
Sure!

**Comment by matthieuauger** [comment]
Hello @banch12, are you still working on this issue?

**Comment by banch12** [comment]
Hi,

I could not start working, as I had to travel to India for family emergency (my uncle passed away) and to take care of family matters.
I will be able to start working on it most likely by end of next week.

Hope it is ok.

BR,
Prashant
________________________________

**Comment by matthieuauger** [comment]
Hello @banch12, very sorry for your loss. Feel free to continue on this issue when the time is right for you.

**Comment by banch12** [comment]
Hello,

I have been busy with family emergency, and was planning to pick up this task after Xmas.

But please go ahead if this is urgent.

Best Regards,
Prashant
________________________________
